name: Persubmit Checks
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  run_tests:
    name: Run Tests
    strategy:
      matrix:
        taichi:
          - 0.6.7
          - 0.6.8
        python:
          - 3.6
          - 3.7
          - 3.8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Taichi
        run: |
          pip install taichi==${{ matrix.taichi }}

      - name: Functionallity Test
        run: |
          export PYTHONPATH=`pwd`
          pytest tests

  check_format:
    name: Check Code Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install YAPF
        run: |
          pip install yapf

      - name: Run YAPF
        run: |
          yapf --style style.yapf -ir .

      - name: Check Git Diff
        run: |
          git diff --exit-code
